export default [
    {
        h2: 'Team Lead',
        preview: '',
        description: 'photo Andrey-S',
        name: 'Andrey',
        github: 'https://github.com/DaniilOvsyanniukov',
    },
    {
        h2: 'scrum master',
        preview: '',
        description: 'photo Vadim',
        name: 'Vadim',
        github: 'https://github.com/anna-stasya',
    },
    {
        h2: 'Developer',
        preview: '',
        description: 'photo ',
        name: 'Ihor',
        github: 'https://github.com/YarPetru',
    },
    {
        h2: 'Developer',
        preview: '',
        description: 'photo Maks',
        name: 'Maks',
        github: 'https://github.com',
    },
    {
        h2: 'Developer',
        preview: '',
        description: 'photo Vika',
        name: 'Vika',
        github: 'https://github.com/AKutusenko',
    },
    {
        h2: 'Developer',
        preview: '',
        description: 'photo Eugene Ivanov',
        name: 'Eugene Ivanov',
        github: 'https://github.com',
    },
    {
        h2: 'Developer',
        preview: '',
        description: 'photo Ihor Pshenychnyi',
        name: 'Ihor Pshenychnyi',
        github: 'https://github.com/',
    },
    {
        h2: 'Developer',
        preview: '',
        description: 'photo Ihor Pshenychnyi',
        name: 'Ihor Pshenychnyi',
        github: 'https://github.com/',
    },
    {
        h2: 'Developer',
        preview: '',
        description: 'photo Ihor Pshenychnyi',
        name: 'Ihor Pshenychnyi',
        github: 'https://github.com',
    },
];